### ISSUE TITLE
step 3 

### ISSUE THREAD

**Issue by nassssro0444** [allinbit/btc_puzzle#2]
lets suppose i m working on puzzle 67 how its supposed to be this step 
Step 3: Modify the 'process' value, initial is {Process(target=worker, args=(31, 35, stop_event))}, change '31' to the number of 0 and '35' to number of 1

can u clarify it more ?

**Comment by allinbit** [comment]
target_hash = "739437bb3dd6d1983e66629c5f08c70e52769371"
private_key_bin = '0' * (256 - 67) + private_key_bin
process = Process(target=worker, args=(33, 34, stop_event)) // This assumes that puzzle 67's privatekey in binary contains 33 zeros and 34 ones

BTW this script is just for fun. You may **never** find the private key. It's just depend on your luck.
